### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#126]
The `npm` build of the site is currently broken. Getting the following in the build log:

```

ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 896: no callout found for <1>
--
  | ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 897: no callout found for <2>
  | ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 898: no callout found for <3>
  | ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 899: no callout found for <4>
  | ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 900: no callout found for <5>
  | ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 901: no callout found for <6>
  | ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 902: no callout found for <7>
  | ERROR 2019/02/06 20:43:46 articles/openshift-ha-installation.adoc: asciidoctor: WARNING: <stdin>: line 903: no callout found for <8>
...
[20:43:47] 'build' errored after 579 ms
[20:43:47] Error: Hugo build failed
    at formatError (/opt/app-root/src/node_modules/gulp-cli/lib/versioned/^3.7.0/format-error.js:20:10)
    at Gulp.<anonymous> (/opt/app-root/src/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:116:13)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/opt/app-root/src/node_modules/orchestrator/index.js:264:8)
    at /opt/app-root/src/node_modules/orchestrator/index.js:275:23
    at finish (/opt/app-root/src/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/opt/app-root/src/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/opt/app-root/src/gulpfile.babel.js:123:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm info lifecycle uncontained.io@1.0.0~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uncontained.io@1.0.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uncontained.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 5092ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2019-02-06T20_43_47_202Z-debug.log
error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/uncontained/builder@sha256:83a9f5ea16a6f8d786702599420b586b7fce9f3d0cab043b05370f4741af5ed5

```

**Comment by etsauer** [comment]
fixed with #128
