### ISSUE TITLE
Need to decouple local build env from local-dev container

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#144]
Currently, the uncontained-local-dev image consumes the local build cache (e.g. node_modules, etc.) from the mounted project directory.

This can lead to build errors when the local npm bindings are not the same as the bindings in the image. For example:

```
$ docker run -u $(id -u) -v ${PWD}:/uncontained.io:Z -it --net=host quay.io/redhat-cop/uncontained-local-dev run build
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.

audited 10423 packages in 5.093s
found 6 vulnerabilities (3 low, 2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> uncontained.io@1.0.0 build /uncontained.io
> gulp build

/uncontained.io/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /uncontained.io/node_modules/node-sass/vendor/linux-x64-64/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 11.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/uncontained.io/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/uncontained.io/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/uncontained.io/node_modules/gulp-sass/index.js:162:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uncontained.io@1.0.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uncontained.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /uncontained.io/.npm/_logs/2019-03-25T17_20_25_638Z-debug.log
```

We should figure out a way to have the image mount the local project more cleanly, maybe by a selective copy.

@JaredBurck @mwitzenm @rdebeasi

**Comment by dobozysaurus** [comment]
I ran into this yesterday as a newcomer to the project - running MacOS locally, so I got an issue with the bindings on the image. I can take a look at this one unless someone else wants it.
