### ISSUE TITLE
Running the Live Preview fail

### ISSUE THREAD

**Issue by Jooho** [redhat-cop/uncontained.io#180]
According to `Contributing to Uncontained.io`, I tried to run local server but failed.

~~~
git clone https://github.com/redhat-cop/uncontained.io.git
cd uncontained.io/

docker run -u $(id -u) \
  -v ${PWD}:/uncontained.io:Z -it \
  --net=host quay.io/redhat-cop/uncontained-local-dev
~~~

Error message
~~~
[13:29:23] Starting 'search'...
[13:29:23] Finished 'search' after 208 ms
[13:29:23] Starting '<anonymous>'...
[13:29:23] '<anonymous>' errored after 27 ms
[13:29:23] Error: ENOSPC: System limit for number of file watchers reached, watch 'site/themes'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1254:11)
    at createFsWatchInstance (/uncontained.io/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/uncontained.io/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/uncontained.io/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/uncontained.io/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/uncontained.io/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/uncontained.io/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqWrap.oncomplete (fs.js:155:5)
[13:29:23] 'server' errored after 1.32 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uncontained.io@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uncontained.io@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /uncontained.io/.npm/_logs/2019-09-12T13_29_24_010Z-debug.log
~~~

**Comment by etsauer** [comment]
@Jooho this just means that you need to increase the number of file watchers allowed on your system.

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by JaredBurck** [comment]
Please reopen if solution above does not work!  Thanks and closing issue!
